CREATE TABLE esm.employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    email_id VARCHAR(255) NOT NULL,
    CONSTRAINT uk_employees_email UNIQUE (email_id)
);

-- Access is through the backend's owning role, not Supabase's Data API.
-- Owners bypass RLS; other roles have no access without explicit policies.
ALTER TABLE esm.employees ENABLE ROW LEVEL SECURITY;
